### ISSUE TITLE
Tidy up REPL code

### ISSUE THREAD

**Issue by danstewart** [danstewart/BFI#2]
[TODO link](https://github.com/danstewart/BFI/blob/c31465f622d12d44f549280ee65ae06305cd603f/bf.pl#L31)

**Comment by npochhi** [comment]
Hi! I'd like to work on this one..

**Comment by danstewart** [comment]
@npochhi Feel free. Let me know if you need any help.

**Comment by danstewart** [comment]
Closed: #6
