### ISSUE TITLE
Hello World fails

### ISSUE THREAD

**Issue by rdebath** [danstewart/BFI#9]
This program should print "Hello World!"
``` bf
+[>[<-[]>+[>+++>[+++++++++++>][>]-[<]>-]]++++++++++<]>
>>>>>----.<<+++.<-..+++.<-.>>>.<<.+++.------.>-.<<+.<.
```

**Comment by richardleach** [comment]
Had a quick look into this and a number of other sample BF test programs. Tracking of nested [] seems buggy and I've got a patch that improves the situation but isn't yet a complete fix.

Some test programs also assume that cells are constrained to values between 0 - 255. e.g.

```
my %symbolmap = (
  '+' => sub { $cells{$pos}++;
							 $cells{$pos} = 0 if ($cells{$pos} > 255);
							},
	'-' => sub { ($cells{$pos} == 0) ?
								$cells{$pos} = 255 :
								$cells{$pos}--;
							},
	'>' => sub { $pos++; $cells{$pos} = 0 if not defined $cells{$pos} },
	'<' => sub { $pos-- if $pos },
	'.' => sub { $output .= chr $cells{$pos} },
	',' => \&in
);
```
(There may be an off-by-one in there, still looking at it.)
